name: CI

on: [push]

jobs:
  build:
    runs-on: maven
    steps:
      - uses: actions/checkout@v1
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          bash ./mvn clean compile
